name: Publish OCI Image using API

on: 
  workflow_dispatch:

jobs:
  updateSubClaim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Optionally : build and minify
      - name: Create archive
        run: |
          wdir=$(pwd)
          echo ${wdir}
          mkdir -p /tmp
          tar -czvf /tmp/release.tar.gz .             
      - name: verify
        run: |          
          ls -ltr /tmp | grep tar.gz      
      - name: API Publish using GITHUB_TOKEN
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/actions/package \
          --header 'authorization: Bearer ${{ github.token }}' \
          --header 'content-type: application/octet-stream' \
          --header 'tag: 1.0.1-actionsdemo' \
          --data-binary "@/tmp/release.tar.gz" \
          --fail
